const { Productos } = require("../models");

const productosFalsos = [
  {
    tipo: "jugador",
    nombre: "Lionel",
    apellido: "Messi",
    posicion: "delantero",
    pais: "Argentina",
    stock: 1,
    precio: 2000,
    rareza: 1,
    urlImagen:
      "https://www.cronista.com/files/image/479/479650/632c94d41dc87.jpg",
  },
  {
    tipo: "jugador",
    nombre: "Franco",
    apellido: "Armani",
    posicion: "portero",
    pais: "Argentina",
    stock: 200,
    precio: 100,
    rareza: 1,
    urlImagen:
      "https://http2.mlstatic.com/D_NQ_NP_827829-MLA51882763339_102022-V.jpg",
  },
  {
    tipo: "jugador",
    nombre: "Cristian",
    apellido: "Romero",
    posicion: "defensor",
    pais: "Argentina",
    stock: 10,
    precio: 200,
    rareza: 1,
    urlImagen:
      "https://http2.mlstatic.com/D_NQ_NP_731723-MLA51863587656_102022-V.jpg",
  },
  {
    tipo: "pelota",
    nombre: "Al Rihla",
    stock: 10,
    precio: 2000,
    rareza: 1,
    urlImagen:
      "https://http2.mlstatic.com/D_NQ_NP_720396-MLA51796279764_102022-V.jpg",
  },
  {
    tipo: "estadio",
    nombre: "Lusail Stadium",
    stock: 10,
    precio: 2000,
    rareza: 1,
    urlImagen:
      "https://figuritasqatar.com.ar/wp-content/uploads/lusail-stadium-2.png",
  },
  {
    tipo: "jugador",
    nombre: "Darwin",
    apellido: "Núñez",
    posicion: "delantero",
    pais: "Uruguay",
    stock: 999,
    precio: 1,
    rareza: 1,
    urlImagen:
      "https://figuritasqatar.com.ar/wp-content/uploads/darwin-nunez-231x300.png",
  },
  {
    tipo: "jugador",
    nombre: "Karim",
    apellido: "Boudiaf",
    posicion: "central",
    pais: "Qatar",
    stock: 500,
    precio: 200,
    rareza: 1,
    urlImagen:
      "https://figuritasqatar.com.ar/wp-content/uploads/karim-boudiaf.png",
  },
  {
    tipo: "jugador",
    nombre: "Musaab",
    apellido: "Khidir",
    posicion: "defensor",
    pais: "Qatar",
    stock: 1,
    precio: 200,
    rareza: 500,
    urlImagen:
      "https://figuritasqatar.com.ar/wp-content/uploads/musaab-khidir.png",
  },
  {
    tipo: "jugador",
    nombre: "Saad",
    apellido: "Al Sheeb",
    posicion: "portero",
    pais: "Qatar",
    stock: 500,
    precio: 200,
    rareza: 1,
    urlImagen:
      "https://figuritasqatar.com.ar/wp-content/uploads/saad-al-sheeb.png",
  },
  {
    tipo: "jugador",
    nombre: "Akram",
    apellido: "Hassan Afif",
    posicion: "delantero",
    pais: "Qatar",
    stock: 500,
    precio: 200,
    rareza: 1,
    urlImagen:
      "https://figuritasqatar.com.ar/wp-content/uploads/akram-hassan-afif.png",
  },
  {
    tipo: "jugador",
    nombre: "Alexander",
    apellido: "Dominguez",
    posicion: "portero",
    pais: "Ecuador",
    stock: 500,
    precio: 200,
    rareza: 1,
    urlImagen:
      "https://figuritasqatar.com.ar/wp-content/uploads/alexander-dominguez.png",
  },
  {
    tipo: "jugador",
    nombre: "Byron",
    apellido: "Castillo",
    posicion: "defensor",
    pais: "Ecuador",
    stock: 500,
    precio: 200,
    rareza: 1,
    urlImagen:
      "https://figuritasqatar.com.ar/wp-content/uploads/bryon-castillo-231x300.png",
  },
  {
    tipo: "jugador",
    nombre: "Moises",
    apellido: "Caicedo",
    posicion: "central",
    pais: "Ecuador",
    stock: 500,
    precio: 200,
    rareza: 1,
    urlImagen:
      "https://figuritasqatar.com.ar/wp-content/uploads/moises-caicedo.png",
  },
  {
    tipo: "jugador",
    nombre: "Enner",
    apellido: "Valencia",
    posicion: "delantero",
    pais: "Ecuador",
    stock: 500,
    precio: 200,
    rareza: 1,
    urlImagen:
      "https://figuritasqatar.com.ar/wp-content/uploads/alexander-dominguez.png",
  },
  {
    tipo: "jugador",
    nombre: "Edouard",
    apellido: "Mendy",
    posicion: "portero",
    pais: "Senegal",
    stock: 500,
    precio: 200,
    rareza: 1,
    urlImagen:
      "https://figuritasqatar.com.ar/wp-content/uploads/edouard-mendy.png",
  },
  {
    tipo: "jugador",
    nombre: "Ibrahima",
    apellido: "Mbaye",
    posicion: "defensor",
    pais: "Senegal",
    stock: 500,
    precio: 200,
    rareza: 1,
    urlImagen:
      "https://figuritasqatar.com.ar/wp-content/uploads/ibrahima-mbaye.png",
  },
  {
    tipo: "jugador",
    nombre: "Pape",
    apellido: "Gueye",
    posicion: "central",
    pais: "Senegal",
    stock: 500,
    precio: 200,
    rareza: 1,
    urlImagen:
      "https://figuritasqatar.com.ar/wp-content/uploads/pape-gueye.png",
  },
  {
    tipo: "jugador",
    nombre: "Sadio",
    apellido: "Mane",
    posicion: "delantero",
    pais: "Senegal",
    stock: 500,
    precio: 200,
    rareza: 1,
    urlImagen:
      "https://figuritasqatar.com.ar/wp-content/uploads/sadio-mane.png",
  },
  {
    tipo: "jugador",
    nombre: "Jasper",
    apellido: "Cillessen",
    posicion: "portero",
    pais: "Paises Bajos",
    stock: 500,
    precio: 200,
    rareza: 1,
    urlImagen:
      "https://figuritasqatar.com.ar/wp-content/uploads/jasper-cillessen.png",
  },
  {
    tipo: "jugador",
    nombre: "Virgil",
    apellido: "Van Dijk",
    posicion: "defensor",
    pais: "Paises Bajos",
    stock: 500,
    precio: 200,
    rareza: 1,
    urlImagen:
      "https://figuritasqatar.com.ar/wp-content/uploads/virgil-van-dijk.png",
  },
  {
    tipo: "jugador",
    nombre: "Frenkie",
    apellido: "De Jong",
    posicion: "central",
    pais: "Paises Bajos",
    stock: 500,
    precio: 200,
    rareza: 1,
    urlImagen:
      "https://figuritasqatar.com.ar/wp-content/uploads/frenkie-de-jong.png",
  },
  {
    tipo: "jugador",
    nombre: "Arnaut",
    apellido: "Danjuma",
    posicion: "delantero",
    pais: "Paises Bajos",
    stock: 500,
    precio: 200,
    rareza: 1,
    urlImagen:
      "https://figuritasqatar.com.ar/wp-content/uploads/arnaut-danjuma.png",
  },
  {
    tipo: "jugador",
    nombre: "Jasper",
    apellido: "Cillessen",
    posicion: "portero",
    pais: "Inglaterra",
    stock: 500,
    precio: 200,
    rareza: 1,
    urlImagen:
      "https://figuritasqatar.com.ar/wp-content/uploads/jasper-cillessen.png",
  },
  {
    tipo: "jugador",
    nombre: "Kyle",
    apellido: "Walker",
    posicion: "defensor",
    pais: "Inglaterra",
    stock: 500,
    precio: 200,
    rareza: 1,
    urlImagen:
      "https://figuritasqatar.com.ar/wp-content/uploads/kyle-walker.png",
  },
  {
    tipo: "jugador",
    nombre: "Mason",
    apellido: "Mount",
    posicion: "central",
    pais: "Inglaterra",
    stock: 500,
    precio: 200,
    rareza: 1,
    urlImagen:
      "https://figuritasqatar.com.ar/wp-content/uploads/mason-mount.png",
  },
  {
    tipo: "jugador",
    nombre: "Harry",
    apellido: "Kane",
    posicion: "delantero",
    pais: "Inglaterra",
    stock: 500,
    precio: 200,
    rareza: 1,
    urlImagen:
      "https://figuritasqatar.com.ar/wp-content/uploads/harry-kane.png",
  },
  {
    tipo: "jugador",
    nombre: "Amir",
    apellido: "Abedzadeh",
    posicion: "portero",
    pais: "Iran",
    stock: 500,
    precio: 200,
    rareza: 1,
    urlImagen:
      "https://figuritasqatar.com.ar/wp-content/uploads/amir-abedzadeh.png",
  },
  {
    tipo: "jugador",
    nombre: "Milad",
    apellido: "Mohammadi",
    posicion: "defensor",
    pais: "Iran",
    stock: 500,
    precio: 200,
    rareza: 1,
    urlImagen:
      "https://figuritasqatar.com.ar/wp-content/uploads/milad-mohammadi.png",
  },
  {
    tipo: "jugador",
    nombre: "Ali",
    apellido: "Gholizadeh",
    posicion: "central",
    pais: "Iran",
    stock: 500,
    precio: 200,
    rareza: 1,
    urlImagen:
      "https://figuritasqatar.com.ar/wp-content/uploads/ali-gholizadeh.png",
  },
  {
    tipo: "jugador",
    nombre: "Saman",
    apellido: "Ghoddos",
    posicion: "delantero",
    pais: "Iran",
    stock: 500,
    precio: 200,
    rareza: 1,
    urlImagen:
      "https://figuritasqatar.com.ar/wp-content/uploads/saman-ghoddos.png",
  },
  {
    tipo: "jugador",
    nombre: "Matt",
    apellido: "Turner",
    posicion: "portero",
    pais: "Estados Unidos",
    stock: 500,
    precio: 200,
    rareza: 1,
    urlImagen:
      "https://figuritasqatar.com.ar/wp-content/uploads/matt-turner.png",
  },
  {
    tipo: "jugador",
    nombre: "Sergiño",
    apellido: "Dest",
    posicion: "defensor",
    pais: "Estados Unidos",
    stock: 500,
    precio: 200,
    rareza: 1,
    urlImagen:
      "https://figuritasqatar.com.ar/wp-content/uploads/sergino-dest.png",
  },
  {
    tipo: "jugador",
    nombre: "Kellyn",
    apellido: "Acosta",
    posicion: "central",
    pais: "Estados Unidos",
    stock: 500,
    precio: 200,
    rareza: 1,
    urlImagen:
      "https://figuritasqatar.com.ar/wp-content/uploads/kellyn-acosta.png",
  },
  {
    tipo: "jugador",
    nombre: "Christian",
    apellido: "Pulisic",
    posicion: "delantero",
    pais: "Estados Unidos",
    stock: 500,
    precio: 200,
    rareza: 1,
    urlImagen:
      "https://figuritasqatar.com.ar/wp-content/uploads/christian-pulisic.png",
  },
  {
    tipo: "equipo",
    nombre: "Italia 1938",
    stock: 500,
    precio: 200,
    rareza: 1,
    urlImagen:
      "https://figuritasqatar.com.ar/wp-content/uploads/italia-1938.png",
  },
  {
    tipo: "equipo",
    nombre: "Uruguay 1930",
    stock: 500,
    precio: 800,
    rareza: 1,
    urlImagen:
      "https://figuritasqatar.com.ar/wp-content/uploads/uruguay-1930.png",
  },
  {
    tipo: "equipo",
    nombre: "Argentina 1978",
    stock: 500,
    precio: 800,
    rareza: 1,
    urlImagen:
      "https://figuritasqatar.com.ar/wp-content/uploads/argentina-1978.png",
  },
  {
    tipo: "equipo",
    nombre: "Francia 1998",
    stock: 500,
    precio: 800,
    rareza: 1,
    urlImagen:
      "https://figuritasqatar.com.ar/wp-content/uploads/francia-1998.png",
  },
  {
    tipo: "equipo",
    nombre: "Brasil 1958",
    stock: 500,
    precio: 800,
    rareza: 1,
    urlImagen:
      "https://figuritasqatar.com.ar/wp-content/uploads/brasil-1958.png",
  },
  {
    tipo: "equipo",
    nombre: "Alemania 1990",
    stock: 500,
    precio: 800,
    rareza: 1,
    urlImagen:
      "https://figuritasqatar.com.ar/wp-content/uploads/alemania-1990.png",
  },
];

module.exports = function () {
  return Productos.bulkCreate(productosFalsos);
};
